import { v4 as uuidv4 } from "uuid";

import agent_1 from "../img/Agent/Agent_1.png";
import agent_2 from "../img/Agent/Agent_2.png";
import agent_3 from "../img/Agent/Agent_3.png";
import agent_4 from "../img/Agent/Agent_4.png";
import agent_5 from "../img/Agent/Agent_1.png";
import agentlist_1 from "../img/Agent/agentlist_1.png";
import agentlist_2 from "../img/Agent/agentlist_2.png";
import agentlist_3 from "../img/Agent/agentlist_3.png";
import agent_list_4 from "../img/Agent/agent_list_4.png";

export const AgentData = {
  topAgent: [
    {
      image: agent_1,
      name: "Benny Chagur",
      degree: "Top Agent",
      id: "1",
    },
    {
      image: agent_2,
      name: "Chynita Heree",
      degree: "Top Agent",
      id: "2",
    },
    {
      image: agent_3,
      name: "David Yers",
      degree: "Top Agent",
      id: "3",
    },
    {
      image: agent_4,
      name: "Hayder Jahid",
      degree: "Top Agent",
      id: "4",
    },
    {
      image: agent_5,
      name: "Benny Chagur",
      degree: "Top Agent",
      id: "5",
    },
  ],
  agentList:[
    {
      profileImage: agentlist_1,
      name: "Karen",
      lastName: "Eilla",
      surname: "Boyette",
      email: "kareneboyette@armyspy.com",
      location: "Manchester",
      phone: "+502-324-4194",
      properties: 15,
      Id: uuidv4(),
      facebook: "https://www.facebook.com/",
      twitter: "http://twitter.com/",
      instagram: "https://www.instagram.com/",
      agentDetails: {
        age: 26,
        city: "New York City",
        state: "New York",
        country: "USA",
        postCode: "1001",
        agentDescription: "Talent customers tend to earn a basic salary in the range of £15,000 to £35,000 per annum. However, talented customers also earn a commission for finding their client's work. Typically, agents receive around 10% of what the client is paid.",
        agency: "All American Real Estate",
        agentLicense: "3124 9764 9700 234",
        taxNumber: "TX 87D0 678H PQ45",
        serviceArea: "Chicago, Los Angeles, New York, Miami beach",
        agentStatus: [
          {
            id: 1,
            title: "Total Listings",
            number: 1050,
            part: [60, 40],
            colors: ["#475BE8", "#F2F6FC"],
          },
          {
            id: 2,
            title: "Properties Sold",
            number: 650,
            part: [50, 50],
            colors: ["#E3A008", "#F2F6FC"],
          },
          {
            id: 3,
            title: "Properties Rent",
            number: 400,
            part: [70, 30],
            colors: ["#E3A008", "#F2F6FC"],
          },
        ],
      },
    },
    {
      profileImage: agentlist_2,
      name: "Walter",
      lastName: "Devid",
      surname: "Moye",
      email: "walterdevidmoye@armyspy.com",
      location: "Chicago, Canada",
      phone: "+457-324-4147",
      properties: 15,
      Id: uuidv4(),
      facebook: "https://www.facebook.com/",
      twitter: "http://twitter.com/",
      instagram: "https://www.instagram.com/",
      agentDetails: {
        age: 26,
        city: "New York City",
        state: "New York",
        country: "USA",
        postCode: "1001",
        agentDescription: "Talent customers tend to earn a basic salary in the range of £15,000 to £35,000 per annum. However, talented customers also earn a commission for finding their client's work. Typically, agents receive around 10% of what the client is paid.",
        agency: "All American Real Estate",
        agentLicense: "3124 9764 9700 234",
        taxNumber: "TX 87D0 678H PQ45",
        serviceArea: "Chicago, Los Angeles, New York, Miami beach",
        agentStatus: [
          {
            id: 1,
            title: "Total Listings",
            number: 1050,
            part: [60, 40],
            colors: ["#475BE8", "#F2F6FC"],
          },
          {
            id: 2,
            title: "Properties Sold",
            number: 650,
            part: [50, 50],
            colors: ["#E3A008", "#F2F6FC"],
          },
          {
            id: 3,
            title: "Properties Rent",
            number: 400,
            part: [70, 30],
            colors: ["#E3A008", "#F2F6FC"],
          },
        ],
      },
    },
    {
      profileImage: agentlist_3,
      name: "David",
      lastName: "Smith",
      surname: "Raddy",
      email: "kareneboyette@armyspy.com",
      location: "Manchester",
      phone: "+584-324-7835",
      properties: 15,
      Id: uuidv4(),
      facebook: "https://www.facebook.com/",
      twitter: "http://twitter.com/",
      instagram: "https://www.instagram.com/",
      agentDetails: {
        age: 26,
        city: "New York City",
        state: "New York",
        country: "USA",
        postCode: "1001",
        agentDescription: "Talent customers tend to earn a basic salary in the range of £15,000 to £35,000 per annum. However, talented customers also earn a commission for finding their client's work. Typically, agents receive around 10% of what the client is paid.",
        agency: "All American Real Estate",
        agentLicense: "3124 9764 9700 234",
        taxNumber: "TX 87D0 678H PQ45",
        serviceArea: "Chicago, Los Angeles, New York, Miami beach",
        agentStatus: [
          {
            id: 1,
            title: "Total Listings",
            number: 1050,
            part: [60, 40],
            colors: ["#475BE8", "#F2F6FC"],
          },
          {
            id: 2,
            title: "Properties Sold",
            number: 650,
            part: [50, 50],
            colors: ["#E3A008", "#F2F6FC"],
          },
          {
            id: 3,
            title: "Properties Rent",
            number: 400,
            part: [70, 30],
            colors: ["#E3A008", "#F2F6FC"],
          },
        ],
      },
    },
    {
      profileImage: agent_list_4,
      name: "Jhon",
      lastName: "Haron",
      surname: "Bably",
      email: "kareneboyette@armyspy.com",
      location: "Chicago, Canada",
      phone: "+502-324-4194",
      properties: 15,
      Id: uuidv4(),
      facebook: "https://www.facebook.com/",
      twitter: "http://twitter.com/",
      instagram: "https://www.instagram.com/",
      agentDetails: {
        age: 26,
        city: "New York City",
        state: "New York",
        country: "USA",
        postCode: "1001",
        agentDescription: "Talent customers tend to earn a basic salary in the range of £15,000 to £35,000 per annum. However, talented customers also earn a commission for finding their client's work. Typically, agents receive around 10% of what the client is paid.",
        agency: "All American Real Estate",
        agentLicense: "3124 9764 9700 234",
        taxNumber: "TX 87D0 678H PQ45",
        serviceArea: "Chicago, Los Angeles, New York, Miami beach",
        agentStatus: [
          {
            id: 1,
            title: "Total Listings",
            number: 1050,
            part: [60, 40],
            colors: ["#475BE8", "#F2F6FC"],
          },
          {
            id: 2,
            title: "Properties Sold",
            number: 650,
            part: [50, 50],
            colors: ["#E3A008", "#F2F6FC"],
          },
          {
            id: 3,
            title: "Properties Rent",
            number: 400,
            part: [70, 30],
            colors: ["#E3A008", "#F2F6FC"],
          },
        ],
      },
    },
    
  ],
};
